image: node:14.11.0

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - build

stages:
  - setup
  - build
  - docker-build

setup:
  stage: setup
  script:
    - echo "setup started"
    - npm install
    - echo "setup completed"
  artifacts:
    when: on_success
    expire_in: never
    paths:
      - node_modules
  only:
    - merge_requests
    - development
  #   changes:
  #     - package.json
  #     - package-lock.json
  allow_failure: false

build:
  stage: build
  image: node
  script:
    - echo "build started"
    - npm run build
    - echo "build completed"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
  only:
    - merge_requests
    - development
    # - master
  dependencies:
    - setup

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - name: docker:19.03.8-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
    - docker info
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    # - docker-compose up -d --build --remove-orphans
    # - docker-compose build --pull
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Registry image:" $CI_REGISTRY_IMAGE
  needs: []
  allow_failure: false
  only:
    - development
    # - master
