version: "2"
services:
  nginx:
    image: cuongdev1998/panoee-studio-development
    ports:
      - 80:80
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - REACT_APP_BASE_URL=http://localhost:3003
    environment:
      - "GENERATE_SOURCEMAP=false"
      - "REACT_APP_BASE_URL=http://localhost:3003"
